### ISSUE TITLE
No such file or directory?

### ISSUE THREAD

**Issue by itsss** [rossgoodwin/neuralsnap#6]
$ python neuralsnap.py aaa models/1.t7 models/2.t7 image/image.jpg
(1.t7 and 2.t7 => 2016-01-12_char-rnn_model_01_rg.t7, 2016-01-12_char-rnn_model_02_rg.t7)
INIT NEURALTALK2 CAPTIONING
Traceback (most recent call last):
  File "neuralsnap.py", line 248, in <module>
    webbrowser.open_new_tab(expander.get_result())
  File "neuralsnap.py", line 80, in get_result
    self.narrate()
  File "neuralsnap.py", line 107, in narrate
    ntalk_proc = subprocess.Popen(ntalk_cmd_list)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError:  **[Errno 2] No such file or directory**

what is the problem?
I executed this command in SSH and Virtual Machine, and i executed 'npm install apidoc -g' but this problem is not solved... Please help!!!

**Comment by daoktar** [comment]
Same problem(( Have you find any solution?

> $ python neuralsnap.py aaa models/1.t7 models/2.t7 image/image.jpg
> (1.t7 and 2.t7 => 2016-01-12_char-rnn_model_01_rg.t7, 2016-01-12_char-rnn_model_02_rg.t7)
> INIT NEURALTALK2 CAPTIONING
> Traceback (most recent call last):
> File "neuralsnap.py", line 248, in 
> webbrowser.open_new_tab(expander.get_result())
> File "neuralsnap.py", line 80, in get_result
> self.narrate()
> File "neuralsnap.py", line 107, in narrate
> ntalk_proc = subprocess.Popen(ntalk_cmd_list)
> File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
> raise child_exception
> OSError: **[Errno 2] No such file or directory**
> 
> what is the problem?
> I executed this command in SSH and Virtual Machine, and i executed 'npm install apidoc -g' but this problem is not solved... Please help!!!
